### ISSUE TITLE
3D view is not working locally

### ISSUE THREAD

**Issue by arunkiitkgp** [cyrillef/extract-view.and.data.api#3]
![2dview](https://cloud.githubusercontent.com/assets/8243617/8695805/36132066-2b05-11e5-9396-a6816d092999.PNG)
![layout](https://cloud.githubusercontent.com/assets/8243617/8695806/3614060c-2b05-11e5-9bb9-29941491bb23.PNG)

2D view, Layout 1 and Layout 2 are working properly but 3D View is not working when rendering the files locally. Please help me

**Comment by cyrillef** [comment]
Hi

can you share the model link on extract.autodesk.io, so I download and test your sample locally?

thx
-cyrille

**Comment by cyrillef** [comment]
closing the issue because no response
