### ISSUE TITLE
Some toolbar buttons are not working in viewer.

### ISSUE THREAD

**Issue by ravi2493** [cyrillef/extract-view.and.data.api#4]
Hi,
I translated my dwg file to viewable files. I downloaded the viewable files and tried to view these files locally. Every thing is working fine but some buttons on tool bar are not working. 

Help me resolve this issue.

Thanks ,
Ravi.

**Comment by cyrillef** [comment]
Hi

can you be a bit more specific in which conditions it stops working and which buttons? I went on this [sample](http://extract.autodesk.io/explore/cyrille-2015-05-22/13358513-V8Enginef3d) this morning and it works fine.

-cyrille

**Comment by cyrillef** [comment]
closing the issue because no response
