### ISSUE TITLE
Cannot download the viewable files

### ISSUE THREAD

**Issue by zhangzbxyz** [cyrillef/extract-view.and.data.api#5]
Hi,
After I click the botton of "viewable files", the console always display the error massage below :

```
#1 - Getting full viewable information
#2a - Filtering objects
#2b - Adding manisfest & metadata files for any .f2d files
#2c - Download each item asynchronously
Download failed for dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6YWJkc2UvQ0RFLnJ2dA==
Something wrong happened during download
Error in downloading fragments! ZIP not created.
```

Help me resolve this issue.

Thanks!

**Comment by carlyu** [comment]
We also has experienced this problem.  does it mean Autodesk block the data extraction services ? 
many thanks for help us to resolve this issues.  
thanks.

**Comment by cyrillef** [comment]
Absolutely not, Can you share the file for me to test and debug?

**Comment by carlyu** [comment]
many thanks for reply.   It had problem in December.  now  http://extract.autodesk.io/   works ok for us.

**Comment by cyrillef** [comment]
Thx for the confirmation :)
