### ISSUE TITLE
uncaught typeerror cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by liudongdong2008** [cyrillef/extract-view.and.data.api#8]
HI,I'm trying to use this project in local model,
I upload the cad file and download the zip project from http://extract.autodesk.io/,
 but when i deploy it use node.js,
"uncaught typeerror cannot read property 'model' of undefined" was found in chrome console,
i don't konw why,could u please help me? Thanks
I'm not good at English, I hope you understand this

**Comment by cyrillef** [comment]
I understand what you're saying, but would need the original file to test. Is that something you can share with us?

**Comment by liudongdong2008** [comment]
thanks for your reply.i found that the computer didn't surpport webgl(no matter the version of chrome).

**Comment by cyrillef** [comment]
ok, you probably need to change your graphic card then - but checkout this article: http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser
